### ISSUE TITLE
Should we add pretty url ? Aka, removes .html extension 

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/testSite#1]
My opinion, no. Because I am certain that a lot of people have linked the site on outside sources thus, if they linked to mario.html then the link will no longer work. But I'm open to opinions.

**Comment by devoxel** [comment]
A support Github Pages jekyll plugin lets us setup redirects.

Here are the [docs on it ](https://help.github.com/articles/redirects-on-github-pages/). It would just be a matter of adding some extra stuff in the yaml.

**Comment by HappyZombies** [comment]
Done. We will apply redirects.
